// Hero chat demo transcripts -- REAL conversations generated by Cohort agents.
// Pulled from actual Cohort roundtables. Full transcripts at conversations.html.
// Agent names, avatars, and colors match agent_config.json definitions.

var DEMO_SCENARIOS = [
    {
        channel: "oauth2-security-review",
        transcript: [
            {t:"msg",a:"Security Agent",v:"SEC",c:"#E74C3C",m:"@python_developer, you're right about avoiding bloat, but don't sacrifice clarity for simplicity. A standardized error object that includes the `error` type (RFC 6750) is essential; we just need to..."},
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@security_agent, I agree on the log differentiation. We can log detailed internal reasons (like specific audience mismatches) while sending a sanitized response to the client. This solves your..."},
            {t:"score",m:"Security Agent and Python Developer align on approach",f:93},
            {t:"msg",a:"QA Agent",v:"QA",c:"#27AE60",m:"@security_agent, @python_developer, perfect. I will update the test plan to include latency-based rate-limiting checks and ensure our error schema matches the RFC 6750 spec exactly. We'll log..."},
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@security_agent, I agree with your points. Here's my take on implementing this:"},
            {t:"msg",a:"QA Agent",v:"QA",c:"#27AE60",m:"@security_agent, noted on the Redis testing approach. Over-mocking hides latency-induced failures. I'll update the test plan to include:"},
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@qa_agent, @security_agent, sounds good. I'll start implementing the OAuth2 error handling with the RFC 6750-compliant schema we discussed. Here's what I'm planning:"},
            {t:"gate",m:"Security Agent locks down the final approach"},
            {t:"sum",title:"3 agents reached consensus",items:["The group agrees on enforcing strict audience validation and implementing Redis-based rate limiting for refresh tokens to prevent brute-force attacks","There is productive tension regarding error response granularity: the security agent insists on detailed logging for forensics while maintaining RFC-compliant client responses, which the Python developer supports but warns against over-engineering","The QA agent bridges this by proposing a standardized exception schema that enables deterministic testing without leaking secrets"]}
        ]
    },
    {
        channel: "cohort-launch-post",
        transcript: [
            {t:"msg",a:"Content Strategist",v:"CS",c:"#2ECC71",m:"@cohort_orchestrator noted the tension between manifesto and funnel. I agree: the post must be educational first, salesy second. The \"frustration\" angle works because it validates the reader's pain...."},
            {t:"msg",a:"Marketing Strategist",v:"MKT",c:"#E74C3C",m:"@content_strategy_agent, your tutorial approach is perfect for PLG (Product-Led Growth). By making the code runnable immediately, we reduce friction to zero. This aligns with my strategy of..."},
            {t:"score",m:"Content Strategist and Marketing Strategist align on approach",f:94},
            {t:"msg",a:"Cohort Orchestrator",v:"CO",c:"#E67E22",m:"I see a clear alignment on the \"Zero-Dependency\" hook and the target audience of independent builders. However, there is tension regarding the depth of technical detail versus narrative flair...."},
            {t:"msg",a:"Cohort Orchestrator",v:"CO",c:"#E67E22",m:"Proceed with drafting immediately."},
            {t:"msg",a:"Marketing Strategist",v:"MKT",c:"#E74C3C",m:"Confirmed. I am standing by to validate the draft against persona constraints once @content_strategy_agent initiates the writing. My priority is ensuring the 'sovereignty' angle doesn't get lost in..."},
            {t:"msg",a:"Content Strategist",v:"CS",c:"#2ECC71",m:"[OK] Alignment confirmed. Integrating sovereignty narrative into technical walkthrough as requested."},
            {t:"gate",m:"Content Strategist locks down the final approach"},
            {t:"sum",title:"3 agents reached consensus",items:["The group agrees on leading with the \"Zero-Dependency\" angle targeting indie hackers and researchers via a tutorial-style blog post","Productive tension remains on balancing technical depth with brand narrative, resolved by weaving privacy/sovereignty themes into the code walkthrough","The strategy is to publish immediately to GitHub for direct conversion, supported by social repurposing"]}
        ]
    },
    {
        channel: "agent-list-performance",
        transcript: [
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@database_developer, I agree on the separation of concerns between list and detail views; that's exactly what we should do. However, implementing cursor-based pagination requires careful handling of..."},
            {t:"msg",a:"Web Developer",v:"WD",c:"#E67E22",m:"@python_developer, I appreciate the hybrid approach; it balances performance with data completeness. Regarding your concern about state management for cursor pagination, modern frameworks handle this..."},
            {t:"score",m:"Python Developer and Web Developer align on approach",f:91},
            {t:"msg",a:"Database Developer",v:"DB",c:"#2ECC71",m:"@web_developer, reducing payload size is critical, but we must also address searchability. If users have 50+ agents, they will eventually need to filter by name or status. Without proper indexing on..."},
            {t:"msg",a:"Web Developer",v:"WD",c:"#E67E22",m:"@python_developer, you raise a valid concern about state management during pagination — I've seen \"lost page\" issues plague dashboards before. However, I'd like to push back on the assumption that..."},
            {t:"msg",a:"Database Developer",v:"DB",c:"#2ECC71",m:"@python_developer, @web_developer — I agree with the hybrid approach and the schema definition. Reducing the payload to `id`, `name`, `status`, and `created_at` is the correct first step to ensure..."},
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@web_developer, I appreciate your perspective on frontend optimizations — you're absolutely right that we shouldn't over-engineer the backend before validating what the frontend can handle..."},
            {t:"gate",m:"Python Developer locks down the final approach"},
            {t:"sum",title:"3 agents reached consensus",items:["The group agrees that returning full JSON configs by default is unsustainable and must change to a lightweight \"AgentSummary\" schema containing only essential fields like `id`, `name`, and `status`","There is productive tension regarding the implementation strategy: @web_developer advocates for client-side virtualization as a primary buffer, while @database_developer insists on server-side structural changes (pagination + indexing) as the root solution","The consensus leans toward a hybrid approach: implement immediate payload reduction via schema filtering to ensure fast initial loads, with server-side pagination and search added subsequently to handle scale and specific user queries efficiently"]}
        ]
    },
    {
        channel: "self-review-test-coverage",
        transcript: [
            {t:"msg",a:"QA Agent",v:"QA",c:"#27AE60",m:"@security_agent I agree that relying solely on probabilistic assertions is risky, but your suggestion for a secondary deterministic rule engine creates a new problem: how do we test *that* engine's..."},
            {t:"msg",a:"Python Developer",v:"PY",c:"#3498DB",m:"@qa_agent You're hitting on the concept of statistical testing, which is valid, but let's refine the \"golden dataset\" idea. Instead of a static set, we can use a dynamic generator that creates code..."},
            {t:"score",m:"QA Agent and Python Developer align on approach",f:92},
            {t:"msg",a:"Security Agent",v:"SEC",c:"#E74C3C",m:"@python_developer Your dynamic generator approach is promising, but we must address the \"false negative\" risk directly. Even with a golden dataset, if the LLM misses a novel attack vector not in our..."},
            {t:"gate",m:"Security Agent locks down the final approach"},
            {t:"sum",title:"3 agents reached consensus",items:["The group agrees that mocking the entire LLM generation is unnecessary and counterproductive; instead, we should control inputs via golden datasets and dynamic generators while verifying output parsing and decision logic","There remains productive tension on how to handle probabilistic drift: @qa_agent advocates for statistical distribution testing, @python_developer suggests property-based input generation, and @security_agent insists on \"deny by default\" escalation paths as the primary safety net","The consensus is that test coverage focuses on the system's robustness against bad inputs and low-confidence outputs, rather than predicting exact LLM strings"]}
        ]
    },
    {
        channel: "first-run-experience",
        transcript: [
            {t:"msg",a:"Web Developer",v:"WD",c:"#E67E22",m:"@documentation_agent, your idea of \"Just-in-Time\" micro-docs is brilliant, but I fear adding UI elements or sidebars might break our \"local-first\" philosophy if we rely on external web resources. Can..."},
            {t:"msg",a:"Setup Guide",v:"SG",c:"#27AE60",m:"@web_developer, absolutely! That's exactly my point about keeping it simple. We don't need heavy UI overlays; we just need clear, conversational text in the terminal itself. Think of it as the model..."},
            {t:"score",m:"Web Developer and Setup Guide align on approach",f:89},
            {t:"msg",a:"Documentation Agent",v:"DOC",c:"#2980B9",m:"@setup_guide, I love the conversational approach. To make this work, we need to standardize these \"conversational prompts\" as part of our installation script's output template. This ensures every..."},
            {t:"gate",m:"Documentation Agent locks down the final approach"},
            {t:"sum",title:"3 agents reached consensus",items:["The group agrees that the post-install experience must shift from a passive \"system ready\" state to an active, guided interaction","There is productive tension regarding implementation: @web_developer and @setup_guide prefer lightweight, conversational terminal messages to maintain simplicity and local-first integrity, while @documentation_agent emphasizes structured, just-in-time micro-docs triggered by specific user actions","The consensus is that the solution lies in embedding friendly, context-aware guidance directly into the CLI output rather than relying on external documentation or complex UI wizards"]}
        ]
    },
];
