"""Form Handler -- generates a drop-in JS snippet for contact form submissions.

Supports multiple backends:
  - "formspree"  -> Formspree.io (free tier: 50 submissions/month)
  - "worker"     -> Cloudflare Worker endpoint (our own, zero cost)
  - "mailto"     -> Fallback mailto: link (no JS needed)

The generated form-handler.js intercepts <form> submits, sends via fetch(),
and shows a success/error message inline -- no page reload.
"""

from __future__ import annotations

FORM_HANDLER_JS = """\
// Form Handler -- generated by Cohort Website Creator
// Intercepts form submissions and POSTs to the configured endpoint.
(function () {
    var forms = document.querySelectorAll("form[data-form-handler]");
    if (!forms.length) {
        // Fallback: grab any form with method=POST that isn't mailto
        forms = document.querySelectorAll('form[method="POST"]');
        forms = Array.prototype.filter.call(forms, function (f) {
            return f.action && f.action.indexOf("mailto:") === -1;
        });
    }

    Array.prototype.forEach.call(forms, function (form) {
        form.addEventListener("submit", function (e) {
            e.preventDefault();

            var btn = form.querySelector('[type="submit"]');
            var originalText = btn ? btn.textContent : "";
            if (btn) {
                btn.disabled = true;
                btn.textContent = "Sending...";
            }

            var data = new FormData(form);
            var endpoint = form.getAttribute("data-form-handler") || form.action;

            // Add metadata
            data.append("_source", window.location.href);
            data.append("_submitted_at", new Date().toISOString());

            fetch(endpoint, {
                method: "POST",
                body: data,
                headers: { "Accept": "application/json" }
            })
            .then(function (res) {
                if (res.ok) {
                    // Show success message
                    var msg = document.createElement("div");
                    msg.className = "form-success";
                    msg.setAttribute("role", "alert");
                    msg.innerHTML = '<p style="color: var(--color-primary, #22c55e); font-weight: 600; padding: 1rem; text-align: center;">Thanks! We\\'ll be in touch shortly.</p>';
                    form.parentNode.insertBefore(msg, form.nextSibling);
                    form.reset();
                    form.style.display = "none";
                } else {
                    throw new Error("Server returned " + res.status);
                }
            })
            .catch(function (err) {
                // Show error inline
                var existing = form.querySelector(".form-error");
                if (existing) existing.remove();
                var msg = document.createElement("div");
                msg.className = "form-error";
                msg.setAttribute("role", "alert");
                msg.innerHTML = '<p style="color: #ef4444; padding: 0.5rem 0;">Something went wrong. Please try again or email us directly.</p>';
                form.appendChild(msg);
                console.error("Form submission error:", err);
            })
            .finally(function () {
                if (btn) {
                    btn.disabled = false;
                    btn.textContent = originalText;
                }
            });
        });
    });
})();
"""


def generate_form_handler_js() -> str:
    """Return the form handler JS snippet."""
    return FORM_HANDLER_JS


def get_form_action_url(backend: str = "formspree", endpoint_id: str = "") -> str:
    """Return the form action URL for the given backend.

    Args:
        backend: "formspree", "worker", or "mailto"
        endpoint_id: Formspree form ID or Worker URL

    Returns:
        URL string to use as the form action attribute.
    """
    if backend == "formspree" and endpoint_id:
        return f"https://formspree.io/f/{endpoint_id}"
    elif backend == "worker" and endpoint_id:
        return endpoint_id
    return "#"
